### PR TITLE
Removed some autogenerated uBlock Origin comments

### PR DESCRIPTION
**Pull request by mtxadmin**
... they look dirty in a production list

### CODE REVIEW

**Comment by spirillen** [comment]
Well there is a simple reason to keeping such comments, Saving time to write a issue, as the rule says what, the comment tells me from where and when.

If you have a suggestion to an alternative, I'm listening.

**Comment by mtxadmin** [comment]
Ok, I understand.

**Comment by spirillen** [comment]
Are you going to close this PR then? or have you put on the thinking-cap?

**Comment by mtxadmin** [comment]
This is your project. Or you cannot decline the request? :-)

Ok, I closed.

**Comment by spirillen** [comment]
It was your suggestion for a change, so I figure it is most reasonable that you have the decision to whether you  would persue you the idea or accept it as is

**Pull request closed without merging**
